---
title: "Final Project Preliminary EDA"
output: html_notebook
---
```{r,warning=FALSE,message=FALSE}
rm(list=ls())
library(readr)
library(DataComputing)
library(tidyverse)
library(party)
```
## Data Access
```{r,warning=FALSE,message=FALSE}
CAR <- read_csv("CAR DETAILS FROM CAR DEKHO.csv")
vehicles <- read_csv("vehicles.csv")
```
## Inspecting the initial data
```{r,warning=FALSE,message=FALSE}
head(CAR,message=FALSE)
head(vehicles,message=FALSE)
```
```{r}
nrow(CAR)
nrow(vehicles)
ncol(CAR)
ncol(vehicles)
```
## Data Wrangling
```{r,warning=FALSE,message=FALSE}
Without_Name_IN <-
  CAR %>%
  group_by(km_driven,fuel,transmission) %>%
  summarise(price =mean(selling_price),total=n())%>%
  spread(key=fuel,value=total,fill=0) %>%
  rename(diesel=Diesel,electric=Electric,Transmission=transmission) %>%
  mutate(country="India")

Without_Name_IN$transmission=tolower(Without_Name_IN$Transmission)
Without_Name_IN
```

```{r,warning=FALSE,message=FALSE}
Without_Name_US <-
  vehicles %>%
  filter(!is.na(price),!is.na(transmission),!is.na(fuel),!is.na(odometer),odometer != 0) %>%
  mutate(km_driven=odometer) %>%
  group_by(km_driven,price,transmission,fuel) %>%
  summarise(total=n()) %>%
   spread(key=fuel,value=total,fill=0)%>%
  mutate(country="America")

Without_Name_US
```
```{r,warning=FALSE,message=FALSE}
Combined_Table <-
  Without_Name_IN %>%
  mutate(price=price*0.014)%>% #change currency unit to usd
 full_join(Without_Name_US)


Combined_Table
```
```{r,warning=FALSE,message=FALSE}
logfit<- lm(log(selling_price)~transmission+year+km_driven+fuel+seller_type+owner, data = CAR)
summary(logfit)
plot(logfit)
```
```{r,warning=FALSE,message=FALSE}
CAR %>%
  ggplot(aes(x=km_driven, y=selling_price, fill=transmission)) +
  facet_wrap(fuel~.) +
  geom_point(aes(color=transmission), alpha=0.6)+
  geom_boxplot(alpha=0.3)+
  xlim(0,350000)+
  ylim(0,3000000)
```
```{r,warning=FALSE,message=FALSE}
vehicles %>%
  filter(!is.na(price),!is.na(transmission),!is.na(fuel),!is.na(odometer),odometer != 0) %>%
  ggplot(aes(x=odometer,y=price,fill=transmission),xlab="km_driven",ylab="selling_price") +
  facet_wrap(fuel~.) +
  geom_point(aes(color=transmission),alpha=0.6)+
  geom_boxplot(alpha=0.3)+
  xlim(0,350000)+
  ylim(0,300000)
```
```{r,warning=FALSE,message=FALSE}
Combined_Table %>%
  ggplot(aes(x=km_driven,y=price,fill=transmission)) +
  geom_point(aes(color=transmission),alpha=0.6)+
  geom_boxplot(alpha=0.5)+
  facet_wrap(country~.)+
  xlim(0,350000)+
  ylim(0,300000)
```
